services:
  weatherpg:
    image: postgres:18.0
    restart: always
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "54321:5432"
    volumes:
        - weatherpg_volume:/var/lib/postgresql

volumes:
  weatherpg_volume: {}